title: "The SAWS Synthesizer Resource"
description: "Free virtual analog subtractive synthesizer"
theme: minima  # Options: hacker, slate, tactile, midnight, architect

# Header Links
header_pages:
  - about.md

# Social Links
youtube_username: KristianPont
github_username: KristianPl
