title: "The SAWS Synthesizer Resource"
description: "Free stereo virtual analog subtractive synthesizer"
remote_theme: pages-themes/dinky
plugins:
  - jekyll-remote-theme

nav_order: 1

kramdown:
  input: GFM # GitHub Flavored Markdown
  syntax_highlighter: rouge



# Social Links
youtube_username: KristianPont
github_username: KristianPl
