title: "The SAWS Synthesizer Resource"
description: "Free stereo virtual analog subtractive synthesizer"
theme: minima  # Options: hacker, slate, tactile, midnight, architect 

# Settings for the Table of Contents and Markdown
kramdown:
  toc_levels: 1..3
  input: GFM # GitHub Flavored Markdown
  syntax_highlighter: rouge

# Header Links (Architect uses these in the sidebar/header)
header_pages:
  - index.md
  - saws_manual.md

# Social Links
youtube_username: KristianPont
github_username: KristianPl
